import React, { createContext, useState, useContext, ReactNode } from 'react';

type Language = 'en' | 'es';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  en: {
    'nav.home': 'Home',
    'nav.recommendations': 'Recommendations',
    'nav.library': 'Library',
    'nav.profile': 'Profile',
    'nav.wrapped': 'Stats',
    'nav.community': 'Community',
    'search.placeholder': 'Search albums...',

    'home.album_of_day': 'Album of the Day',
    'home.start_listening': 'Start Listening',
    'home.save_later': 'Save for Later',
    'home.vibing': 'are vibing to this.',
    'home.your_vibe': 'Your Vibe',
    'home.view_history': 'View Stats',
    'home.streak': 'Current Streak',
    'home.total_minutes': 'Total Minutes',
    'home.badges': 'Badges',
    'home.badges_earned': 'Badges Earned',
    'home.listening_activity': 'Listening Activity',
    'home.recent_badges': 'Recent Badges',
    'home.recommended': 'Recommended for You',
    'home.explore_more': 'Explore More',
    'home.days': 'Days',

    'library.title': 'Your Library',
    'library.filter.all': 'All',
    'library.filter.listened': 'Listened',
    'library.filter.saved': 'Saved',
    'library.search_placeholder': 'Search by album or artist...',
    'library.no_albums': 'No albums found',
    'library.try_adjusting': 'Try adjusting your filters or search query.',
    'library.login_required': 'Sign in to view your library',
    'library.login_desc': 'Connect with Google to track your listening history and save your favorite albums.',

    'friends.title': 'Find Friends',
    'friends.search_placeholder': 'Search by name or handle...',
    'friends.suggested': 'Suggested for You',
    'friends.no_users': 'No users found',
    'friends.following_status': 'Following',
    'friends.rankings': 'Rankings',
    'friends.rankings_title': 'Leaderboard',
    'friends.rankings_subtitle': 'See who has the best daily streak!',
    'friends.find_friends': 'Find Friends',
    'friends.search': 'Search',
    'friends.search_subtitle': 'Search for your friends to follow them.',
    'friends.global_rank': 'Global Rank',
    'friends.friends_rank': 'Friends Rank',
    'friends.no_users_found': 'No users found',
    'friends.no_ranking_data': 'No ranking data available',
    'friends.try_different_search': 'Try a different search term.',
    'friends.start_listening_to_join': 'Start listening to albums to join the leaderboard!',
    'friends.listening_label': 'Listened',
    'friends.login_required': 'Sign in to see your friends',
    'friends.login_desc': 'Connect with Google to follow your friends and see what they are listening to.',

    'rec.mixing_console': 'Mixing Console',
    'rec.fine_tune': 'Fine-tune your algorithm.',
    'rec.global_sounds': 'Global Sounds',
    'rec.deep_cuts': 'Deep Cuts',
    'rec.refresh_feed': 'Refresh Feed',
    'rec.tune_discovery': 'Tune Your Discovery',
    'rec.exploring': 'Exploring',
    'rec.top_pick': 'Top Pick for You',
    'rec.play_now': 'Play Now',
    'rec.expanding_horizons': 'Expanding Your Horizons',
    'rec.discover_sounds': 'Discover sounds outside your usual circle.',
    'rec.match': 'Match',
    'rec.and': 'and',

    'profile.verified': 'Verified User',
    'profile.followers': 'Followers',
    'profile.following': 'Following',
    'profile.follow': 'Follow',
    'profile.edit': 'Edit Profile',
    'profile.badges': 'Badges',
    'profile.badges_achievements': 'Badges & Achievements',
    'profile.activity_feed': 'Activity Feed',
    'profile.listened_to': 'listened to',
    'profile.earned': 'Earned',
    'profile.badge': 'Badge',
    'profile.ago': 'ago',
    'profile.see_all': 'See All',
    'profile.earned_badges': 'Collection',
    'profile.locked_badges': 'Available to Unlock',
    'profile.close': 'Close',

    'badge.early_adopter': 'Early Adopter',
    'badge.desc.early_adopter': 'Joined during the beta phase.',
    'badge.vinyl_head': 'Vinyl Head',
    'badge.desc.vinyl_head': 'Listened to 5 complete albums.',
    'badge.critic_lvl5': 'Critic Lvl 5',
    'badge.desc.critic_lvl5': 'Wrote 5 detailed reviews.',
    'badge.deep_diver': 'Deep Diver',
    'badge.desc.deep_diver': 'Listened to 1 hour of ambient music.',
    'badge.genre_hopper': 'Genre Hopper',
    'badge.desc.genre_hopper': 'Listen to 10 different genres.',
    'badge.socialite': 'Socialite',
    'badge.desc.socialite': 'Reach 100 followers.',
    'badge.streaker': 'Streaker',
    'badge.desc.streaker': 'Achieve a 30-day listening streak.',
    'badge.curator': 'Curator',
    'badge.desc.curator': 'Create 5 public playlists.',
    'badge.influencer': 'Influencer',
    'badge.desc.influencer': 'Get 50 likes on a review.',
    'badge.night_owl': 'Night Owl',
    'badge.desc.night_owl': 'Listen between 2AM and 5AM.',
    'badge.modal.title': 'Badges Collection',
    'badge.modal.subtitle': 'Collect badges by listening to music and building streaks.',
    'badge.modal.earned': 'You have earned',
    'badge.modal.out_of': 'out of',
    'badge.modal.badges_suffix': 'badges.',

    'summary.wrapped': 'Lifetime Stats',
    'summary.journey': 'Your Journey in Sound',
    'summary.subtitle': 'See your listening habits. You explored further than ever before.',
    'summary.at_glance': 'At a Glance',
    'summary.new_albums': 'New Albums',
    'summary.top_genre': 'Top Genre',
    'summary.consistent': 'Consistent',
    'summary.login_required': 'Sign in to view your stats',
    'summary.login_desc': 'Connect with Google to see your detailed listening habits and your musical journey.',

    'chat.initial': "Hey! I'm Al, your music guide. Ask me about the daily album or any music questions!",
    'chat.placeholder': 'Ask about music...',
    'chat.bot_name': 'Al the Music Bot',
    'chat.online': 'Online',
    'chat.send': 'Send',

    'album.listen_spotify': 'Listen on Spotify',
    'album.share': 'Share',
    'album.save': 'Save',
    'album.rate_album': 'Rate this album',
    'album.personal_taste': 'Personal Taste',
    'album.vibe_check': 'How much do you vibe with it?',
    'album.artistic_quality': 'Artistic Quality',
    'album.objective_craft': 'Objective craft and impact.',
    'album.the_debate': 'The Debate',
    'album.comments': 'Comments',
    'album.write_review': 'Write a Review',
    'album.view_all_comments': 'View all comments',
    'album.reply': 'Reply',

    'profile.login_required': 'Sign in to view your profile',
    'profile.login_desc': 'Connect with Google to track your listening history, save albums, and earn badges.',
    'profile.sign_in_google': 'Sign in with Google',

    // Common
    'common.by': 'by',
    'common.view_all': 'View All',
    'common.close': 'Close',
    'common.cancel': 'Cancel',
    'common.save': 'Save',
    'common.loading': 'Loading...',
    'common.access_denied': 'Access Denied',
    'common.unknown': 'Unknown',
    'common.login_required': 'Login Required',
    'common.login_required_desc': 'You need to be logged in to perform this action.',

    // Header
    'header.select_language': 'Select Language',
    'header.logout': 'Logout',
    'header.profile_tooltip': 'Profile',
    'header.search_placeholder': 'Search albums...',

    // Home
    'home.streak_active': 'Active',
    'home.no_badges_yet': 'No badges yet. Start listening!',

    // Profile
    'profile.change_username': 'Change Username',
    'profile.prompt_username': 'Enter your new username:',
    'profile.admin_panel': 'Admin',
    'profile.delete_account': 'Delete Account',
    'profile.confirm_delete_1': 'ARE YOU SURE? This action is irreversible and will delete all your AlbumDelDia data, history, and stats forever.',
    'profile.confirm_delete_2': 'FINAL CONFIRMATION: Do you really want to delete your account?',
    'profile.delete_success': 'Account successfully deleted.',
    'profile.delete_error': 'Error deleting account. Please try again.',
    'profile.requires_recent_login': 'For security, you must have logged in recently to delete your account. Please log out and log back in.',
    'profile.stats_streak': 'Day Streak',
    'profile.stats_minutes': 'Minutes Listened',
    'profile.stats_albums': 'Albums Listened',
    'profile.online': 'Online',
    'profile.sonic_explorer': 'Sonic Explorer',
    'profile.listened_albums': 'Listened Albums',
    'profile.no_listened_albums': 'No listened albums yet.',
    'profile.view_full_history': 'View Full History',
    'profile.recent_activity': 'Recent Activity',
    'profile.no_activity': 'No recent activity.',

    // Activity
    'activity.rated': 'Rated',
    'activity.saved': 'Saved',
    'activity.listened': 'Listened to',
    'activity.earned': 'Earned',
    'activity.badge': 'Badge',
    'activity.to_collection': 'to collection',
    'activity.stars': 'stars',

    // Album
    'album.tracks': 'Tracks',
    'album.min': 'min',
    'album.link_copied': 'Link copied to clipboard!',
    'album.saved_true': 'Saved',
    'album.saved_false': 'Save',
    'album.listened_true': 'Listened',
    'album.listened_false': 'Mark Listened',
    'album.loading_desc': 'Loading description...',
    'album.tracklist': 'Tracklist',
    'album.preview_url': 'Preview',

    // Admin
    'admin.title': 'Admin Dashboard',
    'admin.add_album': 'Add Album',
    'admin.edit_album': 'Edit Album',
    'admin.add_new_album': 'Add New Album',
    'admin.spotify_id': 'Spotify ID',
    'admin.required_for_id': 'Required for ID',
    'admin.title_label': 'Title',
    'admin.artist_label': 'Artist',
    'admin.label_label': 'Label',
    'admin.release_date': 'Release Date',
    'admin.cover_url': 'Cover URL',
    'admin.image_preview': 'Image Preview',
    'admin.spotify_url': 'Spotify URL',
    'admin.apple_music_url': 'Apple Music URL',
    'admin.save_album': 'Save Album',
    'admin.fill_required': 'Please fill in required fields',
    'admin.error_saving': 'Error saving album',
    'admin.delete_confirm': 'Are you sure you want to delete this album?',
    'admin.no_permission': 'You do not have permission to access the admin area.',
    'admin.secure_auth': 'Please secure authentication or contact support if this is an error.',
    'admin.current_user': 'Current User',
    'admin.not_logged_in': 'Not logged in'
  },

  es: {
    'nav.home': 'Inicio',
    'nav.recommendations': 'Recomendaciones',
    'nav.library': 'Biblioteca',
    'nav.profile': 'Perfil',
    'nav.wrapped': 'Estadísticas',
    'nav.community': 'Comunidad',
    'search.placeholder': 'Buscar álbumes...',

    'home.album_of_day': 'El Álbum del Día',
    'home.start_listening': 'Escuchar Ahora',
    'home.save_later': 'Guardar',
    'home.vibing': 'están escuchando esto.',
    'home.your_vibe': 'Tu Vibe',
    'home.view_history': 'Ver Estadísticas',
    'home.streak': 'Racha Actual',
    'home.total_minutes': 'Minutos Totales',
    'home.badges': 'Insignias',
    'home.badges_earned': 'Insignias',
    'home.listening_activity': 'Actividad de Escucha',
    'home.recent_badges': 'Insignias Recientes',
    'home.recommended': 'Recomendado para ti',
    'home.explore_more': 'Explorar Más',
    'home.days': 'Días',

    'library.title': 'Tu Biblioteca',
    'library.filter.all': 'Todos',
    'library.filter.listened': 'Escuchados',
    'library.filter.saved': 'Guardados',
    'library.search_placeholder': 'Buscar por álbum o artista...',
    'library.no_albums': 'No se encontraron álbumes',
    'library.try_adjusting': 'Intenta ajustar tus filtros o búsqueda.',
    'library.login_required': 'Inicia sesión para ver tu biblioteca',
    'library.login_desc': 'Conéctate con Google para seguir tu historial de escucha y guardar tus álbumes favoritos.',

    'friends.title': 'Buscar Amigos',
    'friends.search_placeholder': 'Buscar por nombre o usuario...',
    'friends.suggested': 'Sugerencias',
    'friends.no_users': 'No se encontraron usuarios',
    'friends.following_status': 'Siguiendo',
    'friends.rankings': 'Rankings',
    'friends.rankings_title': 'Clasificación',
    'friends.rankings_subtitle': '¡Mira quién tiene la mejor racha diaria!',
    'friends.find_friends': 'Buscar Amigos',
    'friends.search': 'Buscar',
    'friends.search_subtitle': 'Busca a tus amigos para seguirlos.',
    'friends.global_rank': 'Ranking Global',
    'friends.friends_rank': 'Ranking Amigos',
    'friends.no_users_found': 'No se encontraron usuarios',
    'friends.no_ranking_data': 'No hay datos de clasificación',
    'friends.try_different_search': 'Intenta con otro término de búsqueda.',
    'friends.start_listening_to_join': '¡Empieza a escuchar álbumes para unirte a la clasificación!',
    'friends.listening_label': 'Escuchado',
    'friends.login_required': 'Inicia sesión para ver a tus amigos',
    'friends.login_desc': 'Conéctate con Google para seguir a tus amigos y ver qué están escuchando.',

    'rec.mixing_console': 'Consola de Mezcla',
    'rec.fine_tune': 'Ajusta tu algoritmo.',
    'rec.global_sounds': 'Sonidos Globales',
    'rec.deep_cuts': 'Joyas Ocultas',
    'rec.refresh_feed': 'Actualizar Feed',
    'rec.tune_discovery': 'Sintoniza tu Descubrimiento',
    'rec.exploring': 'Explorando',
    'rec.top_pick': 'Mejor Selección para Ti',
    'rec.play_now': 'Reproducir',
    'rec.expanding_horizons': 'Expandiendo Horizontes',
    'rec.discover_sounds': 'Descubre sonidos fuera de tu círculo habitual.',
    'rec.match': 'Coincidencia',
    'rec.and': 'y',

    'profile.verified': 'Usuario Verificado',
    'profile.followers': 'Seguidores',
    'profile.following': 'Siguiendo',
    'profile.follow': 'Seguir',
    'profile.edit': 'Editar Perfil',
    'profile.badges': 'Insignias y Logros',
    'profile.badges_achievements': 'Insignias y Logros',
    'profile.activity_feed': 'Actividad Reciente',
    'profile.listened_to': 'escuchó a',
    'profile.earned': 'Ganó',
    'profile.badge': 'Insignia',
    'profile.ago': 'hace',
    'profile.see_all': 'Ver Todo',
    'profile.earned_badges': 'Colección',
    'profile.locked_badges': 'Disponibles',
    'profile.close': 'Cerrar',

    'badge.early_adopter': 'Early Adopter',
    'badge.desc.early_adopter': 'Te uniste durante la fase beta.',
    'badge.vinyl_head': 'Cabeza de Vinilo',
    'badge.desc.vinyl_head': 'Escuchaste 5 álbumes completos.',
    'badge.critic_lvl5': 'Crítico Nvl 5',
    'badge.desc.critic_lvl5': 'Escribiste 5 reseñas detalladas.',
    'badge.deep_diver': 'Buzo Profundo',
    'badge.desc.deep_diver': 'Escuchaste 1 hora de música ambient.',
    'badge.genre_hopper': 'Saltador de Géneros',
    'badge.desc.genre_hopper': 'Escucha 10 géneros diferentes.',
    'badge.socialite': 'Socialite',
    'badge.desc.socialite': 'Alcanza 100 seguidores.',
    'badge.streaker': 'En Racha',
    'badge.desc.streaker': 'Consigue una racha de 30 días.',
    'badge.curator': 'Curador',
    'badge.desc.curator': 'Crea 5 playlists públicas.',
    'badge.influencer': 'Influencer',
    'badge.desc.influencer': 'Consigue 50 likes en una reseña.',
    'badge.night_owl': 'Búho Nocturno',
    'badge.desc.night_owl': 'Escucha música entre las 2AM y 5AM.',
    'badge.modal.title': 'Colección de Insignias',
    'badge.modal.subtitle': 'Consigue insignias escuchando música y manteniendo rachas.',
    'badge.modal.earned': 'Has conseguido',
    'badge.modal.out_of': 'de',
    'badge.modal.badges_suffix': 'insignias.',

    'summary.wrapped': 'Estadísticas Globales',
    'summary.journey': 'Tu Viaje Sonoro',
    'summary.subtitle': 'Mira tus hábitos de escucha. Exploraste más lejos que nunca.',
    'summary.at_glance': 'De un Vistazo',
    'summary.new_albums': 'Nuevos Álbumes',
    'summary.top_genre': 'Género Top',
    'summary.consistent': 'Consistente',
    'summary.login_required': 'Inicia sesión para ver tus estadísticas',
    'summary.login_desc': 'Conéctate con Google para ver tus hábitos de escucha detallados y tu viaje musical.',

    'chat.initial': "¡Hola! Soy Al, tu guía musical. ¡Pregúntame sobre el álbum del día o cualquier duda musical!",
    'chat.placeholder': 'Pregunta sobre música...',
    'chat.bot_name': 'Al, el Bot Musical',
    'chat.online': 'En línea',
    'chat.send': 'Enviar',

    'album.listen_spotify': 'Escuchar en Spotify',
    'album.share': 'Compartir',
    'album.save': 'Guardar',
    'album.rate_album': 'Califica este álbum',
    'album.personal_taste': 'Gusto Personal',
    'album.vibe_check': '¿Cuánto vibras con él?',
    'album.artistic_quality': 'Calidad Artística',
    'album.objective_craft': 'Impacto y técnica objetiva.',
    'album.the_debate': 'El Debate',
    'album.comments': 'Comentarios',
    'album.write_review': 'Escribir Reseña',
    'album.view_all_comments': 'Ver todos los comentarios',
    'album.reply': 'Responder',

    'profile.login_required': 'Inicia sesión para ver tu perfil',
    'profile.login_desc': 'Conéctate con Google para seguir tu historial de escucha, guardar álbumes y ganar insignias.',
    'profile.sign_in_google': 'Iniciar sesión con Google',

    // Common
    'common.by': 'por',
    'common.view_all': 'Ver Todo',
    'common.close': 'Cerrar',
    'common.cancel': 'Cancelar',
    'common.save': 'Guardar',
    'common.loading': 'Cargando...',
    'common.access_denied': 'Acceso Denegado',
    'common.unknown': 'Desconocido',
    'common.login_required': 'Inicio de Sesión Requerido',
    'common.login_required_desc': 'Necesitas iniciar sesión para realizar esta acción.',

    // Header
    'header.select_language': 'Seleccionar Idioma',
    'header.logout': 'Cerrar Sesión',
    'header.profile_tooltip': 'Perfil',
    'header.search_placeholder': 'Buscar álbumes...',

    // Home
    'home.streak_active': 'Activo',
    'home.no_badges_yet': 'Aún no hay insignias. ¡Empieza a escuchar!',

    // Profile
    'profile.change_username': 'Cambiar Nombre',
    'profile.prompt_username': 'Introduce tu nuevo nombre de usuario:',
    'profile.admin_panel': 'Panel de Admin',
    'profile.delete_account': 'Eliminar Cuenta',
    'profile.confirm_delete_1': '¿ESTÁS SEGURO? Esta acción es irreversible y eliminará todos tus datos, historial y estadísticas de AlbumDelDia para siempre.',
    'profile.confirm_delete_2': 'CONFIRMACIÓN FINAL: ¿Realmente deseas borrar tu cuenta?',
    'profile.delete_success': 'Cuenta eliminada correctamente.',
    'profile.delete_error': 'Error al eliminar la cuenta. Por favor, inténtalo de nuevo.',
    'profile.requires_recent_login': 'Por seguridad, debes haber iniciado sesión recientemente para borrar tu cuenta. Por favor, cierra sesión y vuelve a entrar.',
    'profile.stats_streak': 'Racha Diaria',
    'profile.stats_minutes': 'Minutos Escuchados',
    'profile.stats_albums': 'Álbumes Escuchados',
    'profile.online': 'En Línea',
    'profile.sonic_explorer': 'Explorador Sónico',
    'profile.listened_albums': 'Álbumes Escuchados',
    'profile.no_listened_albums': 'Aún no has escuchado álbumes.',
    'profile.view_full_history': 'Ver Historial Completo',
    'profile.recent_activity': 'Actividad Reciente',
    'profile.no_activity': 'No hay actividad reciente.',

    // Activity
    'activity.rated': 'Calificó',
    'activity.saved': 'Guardó',
    'activity.listened': 'Escuchó',
    'activity.earned': 'Ganó',
    'activity.badge': 'Insignia',
    'activity.to_collection': 'en su colección',
    'activity.stars': 'estrellas',

    // Album
    'album.tracks': 'Pistas',
    'album.min': 'min',
    'album.link_copied': '¡Enlace copiado al portapapeles!',
    'album.saved_true': 'Guardado',
    'album.saved_false': 'Guardar',
    'album.listened_true': 'Escuchado',
    'album.listened_false': 'Marcar Escuchado',
    'album.loading_desc': 'Cargando descripción...',
    'album.tracklist': 'Lista de Canciones',
    'album.preview_url': 'Previa',

    // Admin
    'admin.title': 'Panel de Administración',
    'admin.add_album': 'Añadir Álbum',
    'admin.edit_album': 'Editar Álbum',
    'admin.add_new_album': 'Añadir Nuevo Álbum',
    'admin.spotify_id': 'ID de Spotify',
    'admin.required_for_id': 'Requerido para ID',
    'admin.title_label': 'Título',
    'admin.artist_label': 'Artista',
    'admin.label_label': 'Sello Musical',
    'admin.release_date': 'Fecha de Lanzamiento',
    'admin.cover_url': 'URL de Portada',
    'admin.image_preview': 'Vista Previa',
    'admin.spotify_url': 'URL de Spotify',
    'admin.apple_music_url': 'URL de Apple Music',
    'admin.save_album': 'Guardar Álbum',
    'admin.fill_required': 'Por favor, rellena los campos requeridos',
    'admin.error_saving': 'Error al guardar el álbum',
    'admin.delete_confirm': '¿Seguro que quieres eliminar este álbum?',
    'admin.no_permission': 'No tienes permiso para acceder al área de administración.',
    'admin.secure_auth': 'Por favor, asegura tu autenticación o contacta con soporte si es un error.',
    'admin.current_user': 'Usuario Actual',
    'admin.not_logged_in': 'No iniciado sesión'
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children?: ReactNode }) => {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string) => {
    return translations[language][key as keyof typeof translations['en']] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};